### ISSUE TITLE
Improved logging and error checking in LibertyPropertiesHoverProvider

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-language-server#295]
I found the following stack trace in the log while using this language server. The problem is that the document object in a LibertyPropertiesHoverProvider object is null and it is used later. 

```
Caused by: java.lang.NullPointerException: Cannot invoke "io.openliberty.tools.langserver.ls.LibertyTextDocument.getUri()" because "tdi" is null
	at io.openliberty.tools.langserver.LibertyConfigFileManager.isServerEnvFile(LibertyConfigFileManager.java:103)
	at io.openliberty.tools.langserver.LibertyConfigFileManager.isConfigFile(LibertyConfigFileManager.java:148)
	at io.openliberty.tools.langserver.hover.LibertyPropertiesHoverProvider.getHover(LibertyPropertiesHoverProvider.java:31)
	at io.openliberty.tools.langserver.LibertyTextDocumentService.hover(LibertyTextDocumentService.java:121)
```

I would like to see the constructor for LibertyPropertiesHoverProvider check that the input parameter is not null and if it is generate a stack trace so we can investigate the problem when it first happens.

**Comment by arunvenmany-ibm** [comment]
@turkeylurkey 
See the changes in liberty-ls/src/main/java/io/openliberty/tools/langserver/LibertyTextDocumentService.java 
We have put some error messages.. Please confirm whether this matches your requirement
